server:
  port: 8080

spring:
  application:
    name: restaurant-reservation
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.restaurant: debug
    org.springframework: info 